name: "setup for ionic"
description: "setup environment"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
        check-latest: true
    - run: npm install
      shell: bash
    - run: npm install -g @ionic/cli
      shell: bash
    - run: ionic capacitor sync
      shell: bash
