name: "setup for ionic"
description: "setup environment"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        check-latest: true
    - name: Cache Node Modules
      id: cache-node-modules
      uses: actions/cache@v3
      with:
        path: node_modules
        key: node-modules-${{ hashFiles('package-lock.json') }}
    - run: npm install
      shell: bash
    - run: npm install -g @ionic/cli
      shell: bash
    - run: ionic capacitor sync
      shell: bash
#    - run: npm run test-ci
#      shell: bash
