version: '3'

volumes:
  nextcloud:
  db:

services:
  db:
    image: mariadb:10.11
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=nextcloud
      - MARIADB_PASSWORD=nextcloud
      - MARIADB_DATABASE=nextcloud
      - MARIADB_USER=nextcloud

  app:
    image: nextcloud:26
    ports:
      - 8080:80
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
      - TRUSTED_PROXIES=127.0.0.1 localhost
      - NEXTCLOUD_TRUSTED_DOMAINS=127.0.0.1 localhost:8100 192.168.178.81:8080 192.168.178.49:8080
