// Mocks generated by Mockito 5.4.2 from annotations
// in deck_ng/test/service/http_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:deck_ng/model/account.dart' as _i2;
import 'package:deck_ng/service/Iauth_service.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAccount_0 extends _i1.SmartFake implements _i2.Account {
  _FakeAccount_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [IAuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIAuthService extends _i1.Mock implements _i3.IAuthService {
  MockIAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Account> getAccount() => (super.noSuchMethod(
        Invocation.method(
          #getAccount,
          [],
        ),
        returnValue: _i4.Future<_i2.Account>.value(_FakeAccount_0(
          this,
          Invocation.method(
            #getAccount,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Account>);
  @override
  dynamic saveCredentials(
    String? url,
    String? username,
    String? password,
    bool? isAuth,
  ) =>
      super.noSuchMethod(Invocation.method(
        #saveCredentials,
        [
          url,
          username,
          password,
          isAuth,
        ],
      ));
}
