// Mocks generated by Mockito 5.4.4 from annotations
// in deck_ng/test/screen/card_details_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:deck_ng/model/card.dart' as _i2;
import 'package:deck_ng/service/Icard_service.dart' as _i3;
import 'package:deck_ng/service/Icredential_service.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCard_0 extends _i1.SmartFake implements _i2.Card {
  _FakeCard_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ICardService].
///
/// See the documentation for Mockito's code generation for more information.
class MockICardService extends _i1.Mock implements _i3.ICardService {
  MockICardService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Card> createCard(
    int? boardId,
    int? stackId,
    String? title,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createCard,
          [
            boardId,
            stackId,
            title,
          ],
        ),
        returnValue: _i4.Future<_i2.Card>.value(_FakeCard_0(
          this,
          Invocation.method(
            #createCard,
            [
              boardId,
              stackId,
              title,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Card>);

  @override
  _i4.Future<_i2.Card> updateCard(
    int? boardId,
    int? stackId,
    int? cardId,
    _i2.Card? card,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCard,
          [
            boardId,
            stackId,
            cardId,
            card,
          ],
        ),
        returnValue: _i4.Future<_i2.Card>.value(_FakeCard_0(
          this,
          Invocation.method(
            #updateCard,
            [
              boardId,
              stackId,
              cardId,
              card,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Card>);

  @override
  _i4.Future<_i2.Card> getCard(
    int? boardId,
    int? stackId,
    int? cardId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCard,
          [
            boardId,
            stackId,
            cardId,
          ],
        ),
        returnValue: _i4.Future<_i2.Card>.value(_FakeCard_0(
          this,
          Invocation.method(
            #getCard,
            [
              boardId,
              stackId,
              cardId,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Card>);

  @override
  _i4.Future<void> deleteCard(
    int? boardId,
    int? stackId,
    int? cardId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteCard,
          [
            boardId,
            stackId,
            cardId,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [ICredentialService].
///
/// See the documentation for Mockito's code generation for more information.
class MockICredentialService extends _i1.Mock
    implements _i5.ICredentialService {
  MockICredentialService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool hasAccount() => (super.noSuchMethod(
        Invocation.method(
          #hasAccount,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  dynamic saveCredentials(
    String? url,
    String? username,
    String? password,
    bool? isAuth,
  ) =>
      super.noSuchMethod(Invocation.method(
        #saveCredentials,
        [
          url,
          username,
          password,
          isAuth,
        ],
      ));

  @override
  String computeAuth(
    dynamic username,
    dynamic password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #computeAuth,
          [
            username,
            password,
          ],
        ),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.method(
            #computeAuth,
            [
              username,
              password,
            ],
          ),
        ),
      ) as String);
}
