// Mocks generated by Mockito 5.4.4 from annotations
// in deck_ng/test/screen/kanban_board_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:ui' as _i9;

import 'package:appflowy_board/appflowy_board.dart' as _i2;
import 'package:deck_ng/controller/board_details_controller.dart' as _i4;
import 'package:deck_ng/model/models.dart' as _i6;
import 'package:flutter/material.dart' as _i5;
import 'package:get/get.dart' as _i3;
import 'package:get/get_state_manager/src/simple/list_notifier.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAppFlowyBoardController_0 extends _i1.SmartFake
    implements _i2.AppFlowyBoardController {
  _FakeAppFlowyBoardController_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRxBool_1 extends _i1.SmartFake implements _i3.RxBool {
  _FakeRxBool_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeInternalFinalCallback_2<T> extends _i1.SmartFake
    implements _i3.InternalFinalCallback<T> {
  _FakeInternalFinalCallback_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [BoardDetailsController].
///
/// See the documentation for Mockito's code generation for more information.
class MockBoardDetailsController extends _i1.Mock
    implements _i4.BoardDetailsController {
  MockBoardDetailsController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AppFlowyBoardController get boardController => (super.noSuchMethod(
        Invocation.getter(#boardController),
        returnValue: _FakeAppFlowyBoardController_0(
          this,
          Invocation.getter(#boardController),
        ),
      ) as _i2.AppFlowyBoardController);

  @override
  set boardController(_i2.AppFlowyBoardController? _boardController) =>
      super.noSuchMethod(
        Invocation.setter(
          #boardController,
          _boardController,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.RxBool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: _FakeRxBool_1(
          this,
          Invocation.getter(#isLoading),
        ),
      ) as _i3.RxBool);

  @override
  int get boardId => (super.noSuchMethod(
        Invocation.getter(#boardId),
        returnValue: 0,
      ) as int);

  @override
  Map<int, _i5.Widget> get myTabs => (super.noSuchMethod(
        Invocation.getter(#myTabs),
        returnValue: <int, _i5.Widget>{},
      ) as Map<int, _i5.Widget>);

  @override
  set boardId(int? value) => super.noSuchMethod(
        Invocation.setter(
          #boardId,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set stackData(List<_i6.Stack>? stacks) => super.noSuchMethod(
        Invocation.setter(
          #stackData,
          stacks,
        ),
        returnValueForMissingStub: null,
      );

  @override
  List<_i6.Stack> get stackData => (super.noSuchMethod(
        Invocation.getter(#stackData),
        returnValue: <_i6.Stack>[],
      ) as List<_i6.Stack>);

  @override
  _i2.AppFlowyBoardController get boardCtl => (super.noSuchMethod(
        Invocation.getter(#boardCtl),
        returnValue: _FakeAppFlowyBoardController_0(
          this,
          Invocation.getter(#boardCtl),
        ),
      ) as _i2.AppFlowyBoardController);

  @override
  _i3.InternalFinalCallback<void> get onStart => (super.noSuchMethod(
        Invocation.getter(#onStart),
        returnValue: _FakeInternalFinalCallback_2<void>(
          this,
          Invocation.getter(#onStart),
        ),
      ) as _i3.InternalFinalCallback<void>);

  @override
  _i3.InternalFinalCallback<void> get onDelete => (super.noSuchMethod(
        Invocation.getter(#onDelete),
        returnValue: _FakeInternalFinalCallback_2<void>(
          this,
          Invocation.getter(#onDelete),
        ),
      ) as _i3.InternalFinalCallback<void>);

  @override
  bool get initialized => (super.noSuchMethod(
        Invocation.getter(#initialized),
        returnValue: false,
      ) as bool);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  int get listeners => (super.noSuchMethod(
        Invocation.getter(#listeners),
        returnValue: 0,
      ) as int);

  @override
  void onReady() => super.noSuchMethod(
        Invocation.method(
          #onReady,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<void> refreshData() => (super.noSuchMethod(
        Invocation.method(
          #refreshData,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  void reorder(
    int? selectedStackIndex,
    int? oldIndex,
    int? newIndex,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #reorder,
          [
            selectedStackIndex,
            oldIndex,
            newIndex,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  dynamic cardReorderHandler(
    int? oldCardIndex,
    int? newCardIndex,
    int? oldListIndex,
    int? newListIndex,
  ) =>
      super.noSuchMethod(Invocation.method(
        #cardReorderHandler,
        [
          oldCardIndex,
          newCardIndex,
          oldListIndex,
          newListIndex,
        ],
      ));

  @override
  void cardSuccessMsg() => super.noSuchMethod(
        Invocation.method(
          #cardSuccessMsg,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void update([
    List<Object>? ids,
    bool? condition = true,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #update,
          [
            ids,
            condition,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onInit() => super.noSuchMethod(
        Invocation.method(
          #onInit,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onClose() => super.noSuchMethod(
        Invocation.method(
          #onClose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void $configureLifeCycle() => super.noSuchMethod(
        Invocation.method(
          #$configureLifeCycle,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Disposer addListener(_i8.GetStateUpdate? listener) => (super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValue: () {},
      ) as _i8.Disposer);

  @override
  void removeListener(_i9.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void refresh() => super.noSuchMethod(
        Invocation.method(
          #refresh,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void refreshGroup(Object? id) => super.noSuchMethod(
        Invocation.method(
          #refreshGroup,
          [id],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyChildrens() => super.noSuchMethod(
        Invocation.method(
          #notifyChildrens,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListenerId(
    Object? id,
    _i9.VoidCallback? listener,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #removeListenerId,
          [
            id,
            listener,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Disposer addListenerId(
    Object? key,
    _i8.GetStateUpdate? listener,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addListenerId,
          [
            key,
            listener,
          ],
        ),
        returnValue: () {},
      ) as _i8.Disposer);

  @override
  void disposeId(Object? id) => super.noSuchMethod(
        Invocation.method(
          #disposeId,
          [id],
        ),
        returnValueForMissingStub: null,
      );
}
