name: "setup for ios"
description: "setup environment"
runs:
  using: "composite"
  steps:
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1' # Not needed with a .ruby-version file
        bundler-cache: true
    - run: |
        brew install fastlane
      shell: bash
