/**
 * nextcloud deck api
 * Title
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BoardPermissions {
    PERMISSION_READ?: boolean;
    PERMISSION_EDIT?: boolean;
    PERMISSION_MANAGE?: boolean;
    PERMISSION_SHARE?: boolean;
}

