/**
 * nextcloud deck api
 * Title
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Label } from './label';
import { BoardItemPermissions } from './boardItemPermissions';
import { BoardItemOwner } from './boardItemOwner';
import { BoardItemSettings } from './boardItemSettings';


export interface BoardItem { 
    title?: string;
    owner?: BoardItemOwner;
    color?: string;
    archived?: boolean;
    labels?: Array<Label>;
    acl?: Array<string>;
    permissions?: BoardItemPermissions;
    users?: Array<number>;
    shared?: number;
    deletedAt?: number;
    id?: number;
    lastModified?: number;
    settings?: BoardItemSettings;
}

