/**
 * nextcloud deck api
 * Title
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Label } from './label';
import { BoardPermissions } from './boardPermissions';
import { BoardOwner } from './boardOwner';
import { BoardSettings } from './boardSettings';


export class Board {

    constructor(public id?: number) {
    }
    title: string;
    owner?: BoardOwner;
    color?: string;
    archived?: boolean;
    labels?: Array<Label>;
    acl?: Array<string>;
    permissions?: BoardPermissions;
    users?: Array<number>;
    shared?: number;
    deletedAt?: number;
    lastModified?: number;
    settings?: BoardSettings;
}

