/**
 * nextcloud deck api
 * Title
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Label { 
    title?: string;
    color?: number;
    boardId?: string;
    lastModified?: string;
    id?: number;
    ETAG?: string;
    cardId?: number;
}

