/**
 * nextcloud deck api
 * Title
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LoginV2Post200ResponsePoll } from './loginV2Post200ResponsePoll';


export interface LoginV2Post200Response { 
    poll?: LoginV2Post200ResponsePoll;
    login?: string;
}

