/**
 * nextcloud deck api
 * Title
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LoginV2Get200ResponsePoll } from './loginV2Get200ResponsePoll';


export interface LoginV2Get200Response { 
    poll?: LoginV2Get200ResponsePoll;
    login?: string;
}

