// This file was generated by package:dart_define, DO NOT modify or remove these comments
class DartDefine {
  DartDefine._();
  
  /// we need the secret from your wiredash.io login
  static const wiredashSecret = String.fromEnvironment('WIREDASH_SECRET');
}

    