name: "setup for flutter and fastlane"
description: "setup environment for flutter and fastlane"
runs:
  using: "composite"
  steps:
    - name: Set up Flutter actions
      uses: subosito/flutter-action@v1
      with:
        flutter-version: '3.19.5'

    - name: Install dependencies
      shell: bash
      run: flutter pub get

    - name: Run Flutter tests
      shell: bash
      run: flutter test

    - name: Set up Fastlane
      shell: bash
      run: |
        cd android
        sudo gem install bundler
        bundle config set path 'vendor/bundle'
        bundle install