# The Deliverfile allows you to store various App Store Connect metadata
# For more information, check out the docs
# https://docs.fastlane.tools/actions/deliver/
#dev_portal_team_id = "125543860"
submit_for_review(true)
automatic_release(true)


