name: "setup for android"
description: "setup environment"
runs:
  using: "composite"
  steps:
    - uses: actions/cache@v3
      with:
        path: |
          ~/android/.gradle/caches
          ~/android/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: 17
        check-latest: true
    - name: install gradle
      shell: bash
      run: |
        cd android
        gradle wrapper

    - name: Generate .jks file
      shell: bash
      run: echo ${{secrets.FASTLANE_ANDROID_SIGNING_KEYSTORE_BASE64 }} | base64 -d > ${{ secrets.FASTLANE_ANDROID_SIGNING_KEYSTORE_PATH }}
      

