name: "setup for android"
inputs:
  branch:
    description: "which branch should checked out?"
    type: string

description: "setup environment"
runs:
  using: "composite"
  steps:
    - uses: actions/cache@v3
      with:
        path: |
          ~/android/.gradle/caches
          ~/android/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: 11
        check-latest: true
    - run: ionic capacitor sync android
      shell: bash
    - run: npm run build-android-ci
      shell: bash
