name: Flutter Build

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Flutter actions
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.19.5'

      - name: Install dependencies
        run: flutter pub get

      - name: Run Flutter tests
        run: flutter test