name: "CI for android"
inputs:
  branch:
    description: "which branch should checked out?"
    type: string

description: "setup environment"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
        check-latest: true
    - run: npm install
      shell: bash
    - run: npm install -g @ionic/cli
      shell: bash
    - run: ionic build
      shell: bash
    #      - run: npx cap doctor
    - run: ionic capacitor update
      shell: bash
    - run: npx cap sync
      shell: bash
