name: "CI for android"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - master

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/
      - uses: actions/cache@v3
        with:
          path: |
            ~/android/.gradle/caches
            ~/android/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: 11
          check-latest: true
      - run: ls -al /home/runner/work/deck-ng/deck-ng/
      - run: ionic capacitor sync android
      - run: npm run build-android-ci
      - uses: actions/upload-artifact@v2
        with:
          name: app bundle
          path: android/app/build/outputs/bundle/release/app-release.aab
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/
      - run: npm run test-ci
      - uses: actions/upload-artifact@v3
        with:
          name: coverage files
          path:
            coverage/ngv
