name: "CI for android"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - master

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt' # See 'Supported distributions' for available options
          java-version: 11
      - run: npm install --location=global @ionic/cli
      - run: npm install
      - run: ionic build
      #      - run: npx cap doctor
      - run: ionic capacitor update
      - run: npx cap sync
      - run: npm run build-android-ci
      - uses: actions/upload-artifact@v2
        with:
          name: app bundle
          path: android/app/build/outputs/bundle/release/app-release.aab
    test: # make sure the action works on a clean machine without building
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - run: npm i -D -E @angular/cli
        - run: npm run test-ci
        - uses: actions/upload-artifact@v2
          with:
            name: debug apk
            path:
              coverage/ngv
