name: "CI for android"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - master

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/ionic
      - uses: ./.github/workflows/android
      - uses: actions/upload-artifact@v3
        with:
          name: app-bundle
          path: android/app/build/outputs/bundle/release/app-release.aab
