name: "CI"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - master

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: checkout
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt' # See 'Supported distributions' for available options
          java-version: 8
      - run: npm install -g ionic
      - run: npm install
#      - run: npx cap doctor
      - run: ionic capacitor update
      - run: npx cap sync
      - run: npm run build-android-ci
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: checkout
      - name: Setup Ionic
        uses: coturiv/setup-ionic@v1.0.4
      - name: run test
        run: |
          npm i -D -E @angular/cli
          npm run test-ci
