name: Flutter iOS Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Flutter actions
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.19.5'

      - name: Install dependencies
        run: | 
          flutter config --no-analytics
          flutter pub get

      - name: Run Flutter tests
        run: flutter test

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - run: |
          cd ios
          brew install fastlane

      - name: Set up Fastlane
        run: |
          cd ios
          sudo gem install bundler
          bundle config set path 'vendor/bundle'
          bundle install

      - name: Build iOS
        run: |
          cd ios
          pod install
          bundle exec fastlane ios build
        env:
          BASE64_BASIC_AUTH_CERTS_REPO: ${{ secrets.BASE64_BASIC_AUTH_CERTS_REPO }}
          FASTLANE_APPLE_API_KEY_ID: ${{ secrets.FASTLANE_APPLE_API_KEY_ID }}
          FASTLANE_APPLE_API_ISSUER_ID: ${{ secrets.FASTLANE_APPLE_API_ISSUER_ID }}
          FASTLANE_APPLE_API_KEY: ${{ secrets.FASTLANE_APPLE_API_KEY }}
          DEMO_USER: ${{ secrets.FASTLANE_DEMO_USER }}
          DEMO_PASSWORD: ${{ secrets.FASTLANE_DEMO_PASSWORD }}
          MATCH_PASSWORD: ${{ secrets.FASTLANE_CERT_MATCH_PASSWORD}}

      - name: Upload iOS build
        uses: actions/upload-artifact@v2
        with:
          name: Runner.app
          path: ios/build/ios/iphoneos/Runner.app