name: Android Release

on:
  workflow_dispatch:
    inputs:
      track:
        description: 'Which track should be used? One of beta, production'
        required: true
        default: 'beta'
        options:
          - beta
          - production

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: ./.github/workflows/_flutter_build.yml
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Set up Fastlane
        run: |
          cd android
          sudo gem install bundler
          bundle config set path 'vendor/bundle'
          bundle install

      - name: Build APK
        run: |
          cd android
          bundle exec fastlane android build

      - name: Generate .jks file
        run: echo ${{secrets.FASTLANE_ANDROID_SIGNING_KEYSTORE_BASE64 }} | base64 -d > ${{ secrets.FASTLANE_ANDROID_SIGNING_KEYSTORE_PATH }}

      - name: Release to Google Play
        run: |
          cd android
          bundle exec fastlane android deploy track:${{ github.event.inputs.track }}
        env:
          GOOGLE_PLAY_JSON_KEY_DATA: ${{ secrets.GOOGLE_PLAY_JSON_KEY_DATA }}
          FASTLANE_ANDROID_SIGNING_KEY_PASSWORD: ${{ secrets.FASTLANE_ANDROID_SIGNING_KEY_PASSWORD }}
          FASTLANE_ANDROID_SIGNING_KEYSTORE_PASSWORD: ${{ secrets.FASTLANE_ANDROID_SIGNING_KEYSTORE_PASSWORD }}
          FASTLANE_ANDROID_SIGNING_KEYSTORE_PATH: ${{ secrets.FASTLANE_ANDROID_SIGNING_KEYSTORE_PATH }}