name: Flutter iOS Release2

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: macos-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'
          channel: 'stable'
          cache: true

      - name: Install Dependencies
        run: |
          flutter config --no-analytics
          flutter pub get

      - name: Set up Ruby and CocoaPods
        run: |
          brew install ruby
          gem install bundler
          gem install cocoapods

      - name: Install CocoaPods
        working-directory: ios
        run: |
          pod install

      - name: Build iOS App
        working-directory: ios
        run: |
          bundle config set path 'vendor/bundle'
          bundle install
          bundle exec flutter build ios --release --no-codesign
