name: Flutter Android Release

on:
  workflow_dispatch:
    inputs:
      track:
        description: 'Which track should be used? One of beta, production'
        required: true
        default: 'beta'
        type: choice
        options:
          - beta
          - production

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Flutter actions
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version-file: pubspec.yaml
          cache: true

      - name: Install dependencies
        run: |
          flutter config --no-analytics
          flutter pub get

      - name: Run Flutter tests
        run: flutter test

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: "3.3"

      - name: Set up Fastlane
        run: |
          cd android
          sudo gem install bundler
          bundle config set path 'vendor/bundle'
          bundle install

      - uses: actions/cache@v4
        with:
          path: |
            ~/android/.gradle/caches
            ~/android/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: 17
          check-latest: true
          cache: gradle
          cache-dependency-path: | # optional
            android/*.gradle*
            android/**/gradle-wrapper.properties

      - name: install gradle
        working-directory: android
        run: |
          gradle wrapper --no-daemon

      - name: Generate .jks file
        working-directory: android
        run: echo "${{ secrets.FASTLANE_ANDROID_SIGNING_KEYSTORE_BASE64 }}" | base64 --decode > /tmp/keystore.jks

      - name: Create .env file
        run: echo "WIREDASH_SECRET=${{ secrets.WIREDASH_SECRET }}" > .env

      - name: build_runner
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Release to Google Play
        working-directory: android
        run: |
          bundle exec fastlane android release track:${{ github.event.inputs.track }}
        env:
          GOOGLE_PLAY_JSON_KEY_DATA: ${{ secrets.GOOGLE_PLAY_JSON_KEY_DATA }}
          FASTLANE_ANDROID_SIGNING_KEY_PASSWORD: ${{ secrets.FASTLANE_ANDROID_SIGNING_KEY_PASSWORD }}
          FASTLANE_ANDROID_SIGNING_KEYSTORE_PASSWORD: ${{ secrets.FASTLANE_ANDROID_SIGNING_KEYSTORE_PASSWORD }}
          FASTLANE_ANDROID_SIGNING_KEYSTORE_PATH: "/tmp/keystore.jks"
          WIREDASH_SECRET: ${{ secrets.WIREDASH_SECRET }}