name: Flutter Android Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/_flutter_build.yml
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Set up Fastlane
        run: |
          cd android
          sudo gem install bundler
          bundle config set path 'vendor/bundle'
          bundle install

      - name: Build APK
        run: |
          cd android
          bundle exec fastlane android test

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-release.apk
          path: android/build/app/outputs/flutter-apk/app-release.apk