name: Flutter iOS Release

on:
  workflow_dispatch:
    inputs:
      track:
        description: 'Which track should be used? One of beta, production'
        required: true
        default: 'beta'
        type: choice
        options:
          - beta
          - production

jobs:
  release:
    runs-on: macos-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Flutter actions
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version-file: pubspec.yaml
          cache: true

      - name: Install dependencies
        run: |
          flutter config --no-analytics
          flutter pub get

      - name: Create .env file for testing
        run: |
          echo "WIREDASH_SECRET=${{ secrets.WIREDASH_SECRET_TEST }}" > .env
          echo "WIREDASH_PROJECT_ID=${{ secrets.WIREDASH_PROJECT_ID_TEST }}" >> .env
          flutter pub run build_runner build --delete-conflicting-outputs

      - name: Run Flutter tests
        run: flutter test

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: "3.3"

      - name: Set up Fastlane
        run: |
          cd ios
          sudo gem install bundler
          bundle config set path 'vendor/bundle'
          bundle install

      - name: Create .env file for release
        run: |
          if [ "${{ github.event.inputs.track }}" == "production" ]; then
            echo "WIREDASH_SECRET=${{ secrets.WIREDASH_SECRET }}" > .env
            echo "WIREDASH_PROJECT_ID=${{ secrets.WIREDASH_PROJECT_ID }}" >> .env
            flutter pub run build_runner build --delete-conflicting-outputs
          else
            echo "on track ${{ github.event.inputs.track }}, no new .env files needed"
          fi

      - name: Release iOS
        run: |
          cd ios
          pod install
          bundle exec fastlane ios release track:${{ github.event.inputs.track }}
        env:
          BASE64_BASIC_AUTH_CERTS_REPO: ${{ secrets.BASE64_BASIC_AUTH_CERTS_REPO }}
          FASTLANE_APPLE_API_KEY_ID: ${{ secrets.FASTLANE_APPLE_API_KEY_ID }}
          FASTLANE_APPLE_API_ISSUER_ID: ${{ secrets.FASTLANE_APPLE_API_ISSUER_ID }}
          FASTLANE_APPLE_API_KEY: ${{ secrets.FASTLANE_APPLE_API_KEY }}
          DEMO_USER: ${{ secrets.FASTLANE_DEMO_USER }}
          DEMO_PASSWORD: ${{ secrets.FASTLANE_DEMO_PASSWORD }}
          MATCH_PASSWORD: ${{ secrets.FASTLANE_CERT_MATCH_PASSWORD}}