name: "release for android"
on:
  workflow_dispatch:
    inputs:
      track:
        description: 'which track should be used? One of internal, alpha (means closed), beta (means open), production'
        required: true
        default: 'beta'
        options:
          - beta
          - production
        type: choice
jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/ionic
      - uses: ./.github/workflows/android
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1' # Not needed with a .ruby-version file
          bundler-cache: true
      - name: Generate .jks file
        run: echo ${{secrets.FASTLANE_ANDROID_SIGNING_KEYSTORE_BASE64 }} | base64 -d > ${{ secrets.FASTLANE_ANDROID_SIGNING_KEYSTORE_PATH }}
      - run: bundle exec fastlane android build track:${{ inputs.track }}
        env:
          GOOGLE_PLAY_JSON_KEY_DATA: ${{ secrets.GOOGLE_PLAY_JSON_KEY_DATA }}
          FASTLANE_ANDROID_SIGNING_KEY_PASSWORD: ${{ secrets.FASTLANE_ANDROID_SIGNING_KEY_PASSWORD }}
          FASTLANE_ANDROID_SIGNING_KEYSTORE_PASSWORD: ${{ secrets.FASTLANE_ANDROID_SIGNING_KEYSTORE_PASSWORD }}
          FASTLANE_ANDROID_SIGNING_KEYSTORE_PATH: ${{ secrets.FASTLANE_ANDROID_SIGNING_KEYSTORE_PATH }}
