name: "release for android"
on:
  workflow_dispatch:
    inputs:
      track:
        description: 'which track should be used? One of internal, alpha (means closed), beta (means open), production'
        required: true
        default: 'beta'
        options:
          - internal
          - alpha
          - beta
          - production
        type: choice
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'master'
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt' # See 'Supported distributions' for available options
          java-version: 11
      - run: npm install --location=global @ionic/cli
      - run: npm install
      - run: ionic build
      #      - run: npx cap doctor
      - run: ionic capacitor update
      - run: npx cap sync
      - run: npm run build-android-ci
      - uses: r0adkll/sign-android-release@v1
        name: Sign app APK
        # ID used to access action output
        id: sign_app
        with:
          releaseDirectory: android/app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          # override default build-tools version (29.0.3) -- optional
          BUILD_TOOLS_VERSION: "30.0.2"
      - uses: actions/upload-artifact@v2
        with:
          name: app bundle
          path: android/app/build/outputs/bundle/release/app-release.aab
      - name: Upload Android Release to Play Store
        uses: r0adkll/upload-google-play@v1.0.17
        with:
         serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
         packageName: net.meltzow.deckng
         track: ${{ github.event.inputs.track }}
         releaseFiles: android/app/build/outputs/bundle/release/app-release.aab
         status: ${{ github.event.inputs.status }}
