name: "release for ios"
on:
  workflow_dispatch:
    inputs:
      track:
        description: 'which track should be used? beta (means testflight), production'
        required: true
        default: 'beta'
        options:
          - beta
          - production
        type: choice
jobs:
  release:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/ionic
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0' # Not needed with a .ruby-version file
          bundler-cache: true
      - run: |
          brew update
          brew install fastlane
      - run: cd ios/App && pod install
      - run: bundle exec fastlane ios build track:${{ inputs.track }}
        env:
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
          BASE64_BASIC_AUTH_CERTS_REPO: ${{ secrets.BASE64_BASIC_AUTH_CERTS_REPO }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD}}
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_APPLE_USER_PASSWORD }}
          FASTLANE_SESSION: ${{ secrets.FASTLANE_SESSION }}
