name: "release for ios"
on:
  workflow_dispatch:
    inputs:
      device:
        description: 'which track device should be used? '
        required: true
        default: 'iPhone 14'
        options:
          - iPhone 14
          - production
        type: choice
jobs:
  release:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/workflows/ionic
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0' # Not needed with a .ruby-version file
        bundler-cache: true
    - run: |
        brew update
        brew install fastlane
    - run: cd ios/App && pod install  
    - uses: futureware-tech/simulator-action@v2
      with:
        model: ${{ inputs.device }}
    - run: bundle exec fastlane ios snapshots